name: CI/CD for MySQL Database

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Create Docker Volume
      run: docker volume create my-volume

    - name: Run MySQL container with Volume
      run: |
        docker run -d \
          --name mysql-container \
          -v my-volume:/docker-entrypoint-initdb.d \
          -e MYSQL_ROOT_PASSWORD=Balaji@1999 \
          -p 3306:3306 \
          mysql:latest

    - name: Wait for MySQL to start
      run: docker exec mysql-container mysqladmin --silent --wait=30 -uroot -pBalaji@1999 ping

    - name: Copy SQL script into MySQL container
      run: |
        docker cp D:/kiruthiga/DEPLOY_ANGULAR//crud_employee_details.sql mysql-container:/docker-entrypoint-initdb.d/

    - name: Run tests
      run: |
        # Add your test commands here

    - name: Clean up
      run: |
        docker stop mysql-container
        docker rm mysql-container
