name: CI/CD for MySQL Database

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Run MySQL container
      run: |
        docker run -d \
          --name mysql-container \
          -e MYSQL_ROOT_PASSWORD=Balaji@1999 \
          -p 3306:3306 \
          mysql:latest

    - name: Wait for MySQL to start
      run: docker exec mysql-container mysqladmin --silent --wait=30 -uroot -pBalaji@1999 ping

    - name: Run tests
      run: |
        # Add your test commands here
        # Example: docker exec mysql-container mysql -u root -pBalaji@1999 -e "SELECT * FROM employee_details;"

    - name: Deploy SQL scripts
      run: |
        docker cp ./crud_employee_details.sql mysql-container:/docker-entrypoint-initdb.d/
        docker exec mysql-container mysql -u root -pBalaji@1999 your_database < /docker-entrypoint-initdb.d/crud_employee_details.sql

    - name: Clean up
      run: |
        docker stop mysql-container
        docker rm mysql-container
