name: CI/CD for MySQL Database

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Balaji@1999
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Add your test commands here
        docker exec -it a5be0c0e2ed0188c6be399ef5fb84fcea26e9160fd9effe16e6c2b101f5f3b16 mysql -u root -pBalaji@1999 -e "SELECT * FROM employee_details;"

    - name: Build and push Docker image (if needed)
      # If you need to build a Docker image for your application, add the necessary steps here.

    - name: Deploy to Docker container
      run: |
        docker cp ./crud_employee_details.sql a5be0c0e2ed0188c6be399ef5fb84fcea26e9160fd9effe16e6c2b101f5f3b16:/docker-entrypoint-initdb.d/
        docker exec -it a5be0c0e2ed0188c6be399ef5fb84fcea26e9160fd9effe16e6c2b101f5f3b16 mysql -u root -pBalaji@1999 your_database < /docker-entrypoint-initdb.d/crud_employee_details.sql

    - name: Clean up
      run: |
        docker stop a5be0c0e2ed0188c6be399ef5fb84fcea26e9160fd9effe16e6c2b101f5f3b16
        docker rm a5be0c0e2ed0188c6be399ef5fb84fcea26e9160fd9effe16e6c2b101f5f3b16
